server:
  port: 15000 #?????????

spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: cloud-eureka-service
  client:
    registerWithEureka: true #?????????????
    fetchRegistry: false #??????
    serviceUrl: #??????????????????????
      defaultZone: http://localhost:15000/eureka/
